"""empty message

Revision ID: 492e4fba549f
Revises: ff6d307591b4
Create Date: 2020-08-03 18:37:14.330683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492e4fba549f'
down_revision = 'ff6d307591b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('latitudine', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('longitudine', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'longitudine')
    op.drop_column('events', 'latitudine')
    # ### end Alembic commands ###
